#!/usr/bin/env node

import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

// Read package.json
const packageJsonPath = join(import.meta.dirname, "..", "package.json");
const packageJson = JSON.parse(readFileSync(packageJsonPath, "utf-8")) as {
    version: string;
};

// Define the packageInfo.ts content
const packageInfoContent = `// This file was generated by scripts/updatePackageVersion.ts - Do not edit it manually.
export const packageInfo = {
    version: "${packageJson.version}",
    mcpServerName: "MongoDB MCP Server",
};
`;

// Write to packageInfo.ts
const packageInfoPath = join(import.meta.dirname, "..", "src", "common", "packageInfo.ts");
writeFileSync(packageInfoPath, packageInfoContent);
