#!/bin/bash

if [ ! "$(which git-secrets)" ]
then
   echo "git-secrets is not installed. Please run 'brew install git-secrets' or visit https://github.com/awslabs/git-secrets#installing-git-secrets"
   exit 1
fi

git-secrets --register-aws > /dev/null
git-secrets --scan
